# Generated by Django 4.0 on 2022-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='This is my profile', max_length=500),
        ),
    ]
