# Generated by Django 4.0 on 2022-11-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
    ]
